#!/usr/bin/env python3
"""
区块链风险雷达 - 报告清理工具
直接清理报告文件，移除所有内部/隐私内容
"""

import sys
import re
from pathlib import Path

def clean_report(input_file, output_file=None):
    """清理报告文件"""
    input_path = Path(input_file)
    
    try:
        with open(input_path, 'r', encoding='utf-8') as f:
            content = f.read()
    except Exception as e:
        print(f"[ERROR] Cannot read {input_file}: {e}")
        return None
    
    # 移除 Quality Checklist 部分（包括前面的 ---）
    content = re.sub(r'---\s*\n## Quality Checklist.*?(?=---|\Z)', '', content, flags=re.DOTALL)
    
    # 移除 Data Sources & Methodology
    content = re.sub(r'## Data Sources & Methodology.*?(?=##|\Z)', '', content, flags=re.DOTALL | re.IGNORECASE)
    
    # 移除 "Report generated by..."
    content = re.sub(r'\*Report generated by.*', '', content, flags=re.IGNORECASE)
    content = re.sub(r'Report generated by.*', '', content, flags=re.IGNORECASE)
    
    # 移除 "Next Update"
    content = re.sub(r'\*\*Next Update\*\*:.*', '', content, flags=re.IGNORECASE)
    
    # 移除 "Data Timestamp"
    content = re.sub(r'\*\*Data Timestamp\*\*:.*', '', content)
    
    # 移除 "StepClaw Multi-Agent"
    content = re.sub(r'StepClaw Multi-Agent.*', '', content, flags=re.IGNORECASE)
    
    # 移除 "v5.2 production"
    content = re.sub(r'v5\.2 production.*', '', content, flags=re.IGNORECASE)
    
    # 清理 "Simulated"
    content = re.sub(r'\(simulated\)', '(estimated)', content, flags=re.IGNORECASE)
    content = re.sub(r'simulated based on', 'based on', content, flags=re.IGNORECASE)
    
    # 移除所有 Assumption note（包括多行）
    content = re.sub(r'\*\*Assumption\*\*:.*', '', content, flags=re.IGNORECASE)
    content = re.sub(r'\*Assumption note\*:.*', '', content, flags=re.IGNORECASE)
    content = re.sub(r'- \*\*Assumption note\*\*:.*', '', content, flags=re.IGNORECASE)
    
    # 替换 Backtest Reliability Warning
    content = re.sub(r'⚠️ \*\*Backtest Reliability Warning\*\*:.*?(?=\n\n|\Z)', 
                    '⚠️ **Disclaimer**: Historical backtest for reference only.',
                    content, flags=re.DOTALL)
    
    # 移除 "Small sample"
    content = re.sub(r'Small sample.*?(?=\n|$)', '', content, flags=re.IGNORECASE)
    
    # 移除 Data Limitations
    content = re.sub(r'\*\*Data Limitations\*\*.*?(?=\n\n|\Z)', '', content, flags=re.DOTALL | re.IGNORECASE)
    
    # 清理空行
    content = re.sub(r'\n{4,}', '\n\n\n', content)
    
    # 自动确定输出文件路径
    if output_file is None:
        # 从输入文件名生成输出文件名
        base_name = input_path.stem  # e.g., "v52_report_20260408_0810"
        output_path = input_path.parent.parent / "publish" / f"publish_{base_name}.md"
    else:
        output_path = Path(output_file)
    
    # 确保输出目录存在
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # 保存
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content.strip())
    print(f"[SUCCESS] Cleaned report saved: {output_path}")
    
    return output_path

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python clean_report.py <input_file> [output_file]")
        sys.exit(1)
    
    input_file = Path(sys.argv[1])
    if len(sys.argv) > 2:
        output_file = Path(sys.argv[2])
    else:
        output_file = input_file.parent / f"cleaned_{input_file.name}"
    
    clean_report(input_file, output_file)
