#!/usr/bin/env python3
"""
区块链风险雷达 - 发布版本生成器
从完整报告中提取发布内容，移除所有内部/隐私信息
"""

import os
import sys
import re
from datetime import datetime
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent
OUTPUT_DIR = BASE_DIR / "output"
PUBLISH_DIR = BASE_DIR / "publish"
PUBLISH_DIR.mkdir(parents=True, exist_ok=True)

def clean_for_publish(full_report):
    """清理报告，移除所有内部/隐私内容"""
    
    # 1. 移除 Quality Checklist 部分（包括中文版本）
    report = re.sub(r'## Quality Checklist.*?(?=##|\Z)', '', full_report, flags=re.DOTALL)
    report = re.sub(r'---\s*\n## Quality Checklist.*?(?=---|\Z)', '', report, flags=re.DOTALL)
    
    # 2. 移除 Data Sources & Methodology 部分
    report = re.sub(r'## Data Sources & Methodology.*?(?=##|\Z)', '', full_report, flags=re.DOTALL | re.IGNORECASE)
    
    # 3. 移除 "Report generated by..." 行
    report = re.sub(r'\*Report generated by.*', '', report, flags=re.IGNORECASE)
    report = re.sub(r'Report generated by.*', '', report, flags=re.IGNORECASE)
    
    # 4. 移除 "Next Update" 行
    report = re.sub(r'\*\*Next Update\*\*:.*', '', report, flags=re.IGNORECASE)
    
    # 5. 移除 "Data Timestamp" 行（保留在TL;DR中）
    report = re.sub(r'\*\*Data Timestamp\*\*:.*', '', report)
    
    # 6. 移除 "StepClaw Multi-Agent" 标记
    report = re.sub(r'StepClaw Multi-Agent.*', '', report, flags=re.IGNORECASE)
    
    # 7. 移除 "v5.2 production report" 等内部标记
    report = re.sub(r'v5\.2 production.*', '', report, flags=re.IGNORECASE)
    
    # 8. 清理 "Simulated" 标注（替换为更中性的表述）
    report = re.sub(r'\(simulated\)', '(estimated)', report, flags=re.IGNORECASE)
    report = re.sub(r'simulated based on', 'based on', report, flags=re.IGNORECASE)
    
    # 9. 清理空行（连续多个空行合并为2个）
    report = re.sub(r'\n{4,}', '\n\n\n', report)
    
    # 10. 移除 "Assumption note" 中的敏感信息
    report = re.sub(r'\*Assumption note\*:.*API.*', '*Assumption note*: Based on market data analysis.', report, flags=re.IGNORECASE)
    report = re.sub(r'\*Assumption note\*:.*', '', report, flags=re.IGNORECASE)  # 直接移除所有assumption note
    
    # 11. 移除 "Backtest Reliability Warning" 中的内部注释
    report = re.sub(r'⚠️ \*\*Backtest Reliability Warning\*\*:.*?(?=\n\n|\Z)', 
                    '⚠️ **Disclaimer**: Historical backtest for reference only. Past performance does not guarantee future results.',
                    report, flags=re.DOTALL)
    
    # 12. 移除 "Small sample" 警告
    report = re.sub(r'Small sample.*?(?=\n|$)', '', report, flags=re.IGNORECASE)
    
    # 13. 清理页脚
    report = re.sub(r'---\s*\*Not financial advice.*', '---\n*Not financial advice.*', report, flags=re.DOTALL)
    
    # 14. 移除 "Data Limitations" 相关内容
    report = re.sub(r'\*\*Data Limitations\*\*.*?(?=\n\n|\Z)', '', report, flags=re.DOTALL | re.IGNORECASE)
    
    return report.strip()

def add_publish_header(report, original_file):
    """添加发布版本标记"""
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M UTC')
    header = f"""# Blockchain Risk Radar - 12H Report
**Published**: {timestamp}
**Version**: Public Release

---

"""
    return header + report

def process_report(input_file):
    """处理单个报告文件"""
    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            full_report = f.read()
    except Exception as e:
        print(f"[ERROR] Cannot read {input_file}: {e}")
        return None
    
    # 清理报告
    cleaned = clean_for_publish(full_report)
    
    # 添加发布标记
    publish_report = add_publish_header(cleaned, input_file)
    
    # 生成发布文件名
    timestamp = datetime.now().strftime('%Y%m%d_%H%M')
    publish_file = PUBLISH_DIR / f"publish_v52_{timestamp}.md"
    
    # 保存
    with open(publish_file, 'w', encoding='utf-8') as f:
        f.write(publish_report)
    
    return publish_file

def main():
    print("="*70)
    print("BLOCKCHAIN REPORT PUBLISH CLEANER")
    print("="*70)
    
    # 检查命令行参数
    if len(sys.argv) > 1:
        input_file = Path(sys.argv[1])
        if not input_file.exists():
            print(f"[ERROR] File not found: {input_file}")
            sys.exit(1)
    else:
        # 自动查找最新的报告
        reports = sorted(OUTPUT_DIR.glob("v52_report_*.md"), key=lambda x: x.stat().st_mtime, reverse=True)
        if not reports:
            print("[ERROR] No reports found in output directory")
            sys.exit(1)
        input_file = reports[0]
        print(f"[INFO] Using latest report: {input_file.name}")
    
    print(f"[INFO] Processing: {input_file}")
    
    # 处理报告
    publish_file = process_report(input_file)
    
    if publish_file:
        print(f"[SUCCESS] Publish version saved: {publish_file}")
        
        # 读取并显示统计
        with open(publish_file, 'r', encoding='utf-8') as f:
            content = f.read()
        
        print(f"  Characters: {len(content):,}")
        print(f"  Lines: {content.count(chr(10)):,}")
        print("\n[SUCCESS] Report ready for Discord publishing")
        print(f"\nNext step: Run review script")
        print(f"  python scripts/review_blockchain_report.py {publish_file}")
    else:
        print("[ERROR] Failed to process report")
        sys.exit(1)

if __name__ == '__main__':
    main()
